name: app_task_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  onboarding: 3.1.0
  get: 4.6.5
  ionicons: 0.1.2
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  firebase_auth_web: ^4.0.0
  google_sign_in: 5.4.0
  flutter: 
    sdk: flutter
  google_sign_in_web: ^0.10.2

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/image/
  uses-material-design: true

